<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="TESTPRG" Id="{da7b43c9-38b1-4c6f-a60e-db64ccc086f5}" SpecialFunc="None">
    <Declaration><![CDATA[
PROGRAM TESTPRG
VAR
  plcopenCommandTest : PLCopenCommand_Test;
  plcopenCallTest : PLCopenCall_Test;
  plcopenGroupTest : PLCOpenCommandGroup_Test;
  plcopenCallGroupTest : PLCOpenCallGroup_Test;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
// Copyright (c) 2024 Loupe (https://loupe.team), provided under the MIT License.

TcUnit.RUN();
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>