<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="PLCOpenNullRemote" Id="{73061230-7a8e-410b-ae26-c14eb801f0aa}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK PLCOpenNullRemote IMPLEMENTS  IPLCOpenCall

]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Aborted" Id="{d3377050-9f4c-49f6-a051-4bcdc44d847d}">
      <Declaration><![CDATA[METHOD Aborted : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Errored" Id="{97c3ac24-72bd-4b21-93c4-11f805822d38}">
      <Declaration><![CDATA[METHOD Errored : BOOL
VAR_INPUT
	ID : INT;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Finished" Id="{6fdf66c9-5086-43d9-b213-c69b23218cc4}">
      <Declaration><![CDATA[METHOD Finished : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Start" Id="{42d0f9af-461f-4d36-bb4c-e7ed19b6748a}">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD Start
VAR_INPUT
	Command	: IPLCOpenCommand;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[//TODO]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>